<?php
    include '../../api/auth.php';

    function generateRandomString($length = 8) {
        $characters = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $charactersLength = strlen($characters);
        $randomString = '';
    
        for ($i = 0; $i < $length; $i++) {
            $randomString .= $characters[random_int(0, $charactersLength - 1)];
        }
    
        return $randomString;
    }
?>

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Timberly-Admin</title>
        <link rel="stylesheet" href="./styles/addSupplier.css">
        <link rel="stylesheet" href="./styles/components/header.css">
        <link rel="stylesheet" href="./styles/components/sidebar.css">
    </head>
    <body>
        <div class="dashboard-container">
            <div style="position: fixed">
                <?php include "./components/sidebar.php" ?>
            </div>
            <div class="page-content" style="margin-left: 300px">
                <?php include "./components/header.php" ?>
                <div class="main-content">
                    <div class="card">
                        <form id="add-supplier-form" class="add-supplier-form" method="POST" action="../../api/addSupplier.php" onsubmit="return validateForm()">
                            <h2 style="margin-left: 15px; margin-bottom: 30px">Add new supplier</h2>
                            <div class="form-group">
                                <!-- First username is auto-generated -->
                                <input type="text" 
                                    id="username" 
                                    name="username" 
                                    hidden
                                    class="input-field"
                                    <?php 
                                    $username = generateRandomString(); ?>
                                    value="<?php echo $username; ?>">
                            </div>
                            <div class="form-group">
                                <label for="name">Supplier Name</label>
                                <input type="text" 
                                    id="name" 
                                    name="name" 
                                    placeholder="Full name" 
                                    required 
                                    class="input-field" 
                                    pattern="^[A-Za-z\s]+$" 
                                    title="Name can only contain alphabets and spaces.">
                            </div>
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input 
                                    type="email" 
                                    id="email" 
                                    name="email"
                                    pattern="[a-z0-9._%+-]+@[a-z09.-]+\.[a-z]{2,}$" 
                                    placeholder="someone@mail.com" 
                                    required 
                                    class="input-field">
                            </div>
                            <div class="form-group">
                                <label for="phone">Phone number</label>
                                <input 
                                    type="tel" 
                                    id="phone" 
                                    name="phone" 
                                    placeholder="07XXXXXXXX" 
                                    required 
                                    class="input-field" 
                                    pattern="^07\d{8}$" 
                                    title="Phone number must start with '07' and contain exactly 10 digits.">
                            </div>
                            <div class="form-group">
                                <label for="address">Address</label>
                                <input 
                                    type="text" 
                                    id="address" 
                                    name="address" 
                                    placeholder="Address" 
                                    required 
                                    class="input-field">
                            </div>
                            <div class="form-group">
                                <!-- Password is autogenerated--> 
                                <input 
                                    type="password" 
                                    id="password" 
                                    name="password" 
                                    hidden
                                    class="input-field"
                                    <?php
                                    $password = generateRandomString();?>
                                    value="<?php echo $password; ?>">
                            </div>
                            <div class="form-buttons button-container">
                                <button onclick="window.location.href='suppliers.php'" class="button outline">Cancel</button>
                                <button type="submit" class="button solid">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <script src="./scripts/addDriver.js"></script>
    </body>
</html>
